name: ES2 Backend Development CI Pipeline

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  simple_build:
    runs-on: ubuntu-latest
    env:
        DJANGO_SECRET_KEY: "erqwer23"
        PYTHON_VERSION: "3.10"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
           python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Dependencies from pipenv
        run: |
            pipenv install
      - name: Run tests
        run: |
            cd src
            pipenv run python manage.py test
